# Generated by Django 4.2.20 on 2025-04-28 19:56

from django.db import migrations, models
import utils.validator


class Migration(migrations.Migration):

    dependencies = [
        ('site_setup', '0005_alter_sitesetup_favicon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitesetup',
            name='favicon',
            field=models.ImageField(blank=True, default='', upload_to='assets/favicon/%Y/%m/', validators=[utils.validator.validate_png]),
        ),
    ]
